services:
  # ...keep existing 'backend' service

  postgres:
    image: postgres:15-alpine
    ports:
      - 8080:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: con_db
      POSTGRES_HOST_AUTH_METHOD: trust